firmware.f450-sku1.url=https://github.com/RealSenseID/applications.ai.vision-platform.rsid-device/releases/download/opensource-sdk-3.6.1/F450_9.16.1.34226_SKU1_SIGNED.bin
firmware.f450-sku1.raw_name=f450_sku1_signed.bin
firmware.f450-sku1.sha=59a375daf66f7f45a4abc0d94a410deb36b35ee6fb7d0c02ff322963fb05e445

firmware.f450-sku2.url=https://github.com/RealSenseID/applications.ai.vision-platform.rsid-device/releases/download/opensource-sdk-3.6.1/F450_9.16.1.34226_SKU2_SIGNED.bin
firmware.f450-sku2.raw_name=f450_sku2_signed.bin
firmware.f450-sku2.sha=0da7abdf9860cb47b6268bf31443f91a6d6daa3c6389ba7907e627152ebeebc5

#firmware.f500.url=https://github.com/RealSenseID/applications.ai.vision-platform.rsid-device/releases/download/opensource-sdk-3.3.0/F500_2.11.1.4_SIGNED.BIN
#firmware.f500.raw_name=f500_release.bin
#firmware.f500.sha=0c733d4eb040f9c8416c3b864dcc7c1becd960b4e4448a7439f54f837979c825

firmware.f500.url=https://github.com/RealSenseID/applications.ai.vision-platform.rsid-device/releases/download/opensource-sdk-3.6.1/F500_2.16.1.34226_SIGNED.BIN
firmware.f500.raw_name=f500_release.bin
firmware.f500.sha=db1b9951a93d07408f38b554621ace968a6f6f5de26c6a820db5e40785cbc22a